### ISSUE TITLE
Sync specific dashboards

### ISSUE THREAD

**Issue by tuan-phan** [mpostument/grafana-sync#12]
@mpostument  
Can you help to implement the function to pull dashboards with specific folders? We'd like to pull some specific folders for the sync action.
Thank you

**Comment by mpostument** [comment]
Hello, thank you for submitting the issue. I will try to implement this in next few days

**Comment by mpostument** [comment]
In [1.4.0](https://github.com/mpostument/grafana-sync/releases/tag/1.4.0) you can specify folder name or id for push and pull command

**Comment by tuan-phan** [comment]
@mpostument 
Thank you so much <3
