### ISSUE TITLE
Docker image for grafana-sync

### ISSUE THREAD

**Issue by telmich** [mpostument/grafana-sync#20]
Hello @mpostument ! This tool looks quite exactly what I was looking for. I would like to use it in the k8s context and was wondering if you are interested in publishing a container?

If not, I'll build one myself (probably based on alpine), but maybe you want to contribute "an official" one.

**Comment by mpostument** [comment]
Hello @telmich I won't be able to work on container this week. But maybe will have time to do it next week. PR with dockerfile is welcome :)

**Comment by bjhartin** [comment]
@mpostument I've opened [PR 30 for this](https://github.com/mpostument/grafana-sync/pull/30).

**Comment by bjhartin** [comment]
@mpostument Do you intend to publish to docker hub?

**Comment by mpostument** [comment]
Docker image is available here https://github.com/mpostument/grafana-sync/pkgs/container/grafana-sync
