### ISSUE TITLE
Document official docker image

### ISSUE THREAD

**Issue by telmich** [mpostument/grafana-sync#42]
Hey!

I was wondering if there is an "official" docker image? Is it by any chance https://hub.docker.com/layers/eyalfirst/grafana-sync/1.4.4/images/sha256-105026f7c1564458824aabede70329784a0cf77d3ef50ca6a2aa1e393f145b9b?context=explore ?

If yes, can we document it in the repo?

**Comment by mpostument** [comment]
Hello, yes there is an official docker image - https://github.com/mpostument/grafana-sync/pkgs/container/grafana-sync
Once I have time I will create documentation for the docker image. But really usage is the same as on non docker version

**Comment by mpostument** [comment]
Added link to docker registry in the documentation. Going to close issue
