### ISSUE TITLE
feature request: Add darvin_arm64 as architecture to output artifacts of this github project (executable binary)

### ISSUE THREAD

**Issue by iptizer** [mpostument/grafana-sync#72]
Current situation:

* Currently only `darwin_x86_64` is built (for mac)
* M1/M2 Mac* use `darwin_arm64` as architecture
* presumeably it is not so difficult to just add this to the go builder. But I am not a Go dude and did not find a solution in the last 4 minutes ;).

Let me know whether this is a 2 mins thing, whether it is super complicated and whether maybe I should look for myself :).

**Comment by mpostument** [comment]
It shouldn't be hard to do. I will try to address this today

**Comment by mpostument** [comment]
New release https://github.com/mpostument/grafana-sync/releases/tag/1.4.10 contain arm build
