### ISSUE TITLE
Support grafana-sync push-dashboards with the same folder

### ISSUE THREAD

**Issue by tuan-phan** [mpostument/grafana-sync#8]
Hi @mpostument ,
I'm trying to use your tool. The problem that all my dashboard want to sync have a tag ="sync" and put into the folder called "sync_folder"
I can pull all dashboards with tag==sync
`./grafana-sync pull-dashboards --apikey="*******" --directory="dashboards" --url http://grafana-dev.dev.jpe2.net --tag=sync`
All of them will save in folder dashboards/sync
I used this command to push them into stg env:
`./grafana-sync push-dashboards --apikey="*****" --directory="dashboards/sync" --url http://grafana-stg.stg.jpe2.net
`
But they are in General folder not in "sync_folder"
I tried to create "sync_folder" in stg env but no luck.
Can we support this case?
Thank you,

**Comment by mpostument** [comment]
Hello @tuan-phan i can add additional parameter such as folderId to command which can be used to specify in which folder to save dashboards

**Comment by mpostument** [comment]
In [1.3.0](https://github.com/mpostument/grafana-sync/releases/tag/1.3.0). You can push dashboards to the nondefault folder https://github.com/mpostument/grafana-sync#push-folders-to-grafana-in-custom-folder

**Comment by tuan-phan** [comment]
@mpostument 
That's awesome. Thank you,
