### ISSUE TITLE
version misconfiguration 

### ISSUE THREAD

**Issue by oveleten** [mpostument/grafana-sync#95]
I download archive with 1.4.10 version, but if I  run grafana-sync --version, I get  version is 1.4.6

Is it just problem with version showing or in it real 1.4.6?

**Comment by mpostument** [comment]
Sorry, the wrong version was printed. I am going to fix this today

**Comment by mpostument** [comment]
Version is fixed in https://github.com/mpostument/grafana-sync/releases/tag/1.5.0
